# Generated by Django 3.1.4 on 2021-01-05 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180907_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Программа', 'verbose_name_plural': 'Программа'},
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Программанын автору'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(verbose_name='Сүрөттөө'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Жарыяланды'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Публикацияга чыксынбы?'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(default=0, verbose_name='Баасы'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Ичиндегилер'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Жарыяланды'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Экранга чыксынбы?'),
        ),
    ]
